### ISSUE TITLE
Backpack + armory fix [failed experiment]

### ISSUE THREAD

**Issue by MaHuJa** [Tier1Operations/tier1units#2]
An option to explore:

Make a "t1backpack_empty", make the normal ones inherit from it, prevent the normal ones from appearing in arsenal in the first place.
When opening arsenal the backpack should be switched for the empty one, thus not duplicating the initial content.
This could be dangerous if it can trigger
http://feedback.arma3.com/view.php?id=19829
and thus the acre warning for it.

Alternatively, it could end up removing the backpack so that you have to add the empty backpack with the desired content.

**Comment by MaHuJa** [comment]
https://community.bistudio.com/wiki/CfgVehicles_Config_Reference
Setting scope=1 should remove it from arsenal

**Comment by Domi1993** [comment]
What you do at the EletricalAge, i never seen you there are you using this mod?? Or do you only some comments!

**Comment by MaHuJa** [comment]
Between running the public server without mods, and this not actually working anywhere near as intended anyway, closing this as as a failed experiment.
